# Generated by Django 3.1.7 on 2021-04-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_shopuserprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='avatar',
        ),
    ]
