# Generated by Django 3.1.7 on 2021-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_shopuserprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='users_avatars'),
        ),
    ]
