# Generated by Django 3.1.7 on 2021-03-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='город')),
                ('phone', models.PositiveIntegerField(default=0, verbose_name='телефон')),
                ('email', models.CharField(max_length=128, verbose_name='имейл')),
                ('address', models.CharField(max_length=300, verbose_name='адрес')),
            ],
        ),
    ]
